name: 'Node.js Build and Test'
description: 'Builds and tests Node.js projects'

runs:
  using: 'composite'
  steps:
    - name: Cache Yarn
      uses: actions/cache@v3
      with:
        path: ~/.yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        
    - name: Build and Test
      shell: bash
      run: |
        yarn install --frozen-lockfile --prefer-offline
        yarn build
        yarn test 