name: 'Node.js Build and Test'
description: 'Builds and tests Node.js projects'

runs:
  using: 'composite'
  steps:
    - name: Cache npm
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        
    - name: Build and Test
      shell: bash
      run: |
        npm ci
        npm run build
        npm test 