name: Pull Request Check

on:
  pull_request:
    branches: [ main, develop, release ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Conventional PR Title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Security Check
        uses: github/codeql-action/analyze@v2
        with:
          languages: javascript, csharp

      - name: Dependency Review
        uses: actions/dependency-review-action@v3 