name: Security Scan

on:
  push:
    branches: [ main, develop, release ]
  pull_request:
    branches: [ main, develop, release ]
  schedule:
    - cron: '0 0 * * 0'  # Co tydzień

jobs:
  security-scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v3

      # CodeQL Analysis
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp, javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      # Secret Scanning
      - name: Secret Scanning
        uses: github/secret-scanning/scan@v1

      # Dependency Review
      - name: Dependency Review
        uses: actions/dependency-review-action@v3 